version: '3.8'
services:
  beets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beets_watcher
    pull_policy: always
    restart: always
    volumes:
      # If you want to use relative paths:
      - ./config:/config
      # Or if you'd rather use absolute NAS paths:
      - ./music/unsorted:/music_unsorted
      - ./music/organized:/music_organized
    environment:
      - TZ=Europe/Madrid
