version: '3.8'
services:
  beets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beets_watcher
    pull_policy: always
    restart: always
    env_file:
      - .env
    volumes:
      # If you want to use relative paths:
      - ./src/config:${BEETS_CONFIG}
      - ./src/plugins:${PLUGINS_PATH}
      # Or if you'd rather use absolute NAS paths:
      - ./data/beets/logs:${LOGS_PATH}
      - ./data/beets/database:${DATABASE_PATH}
      - ./data/music/unsorted:${UNSORTED_DIR}
      - ./data/music/sorted:${SORTED_DIR}
      # Bind the directory
      # - ./data/beets/logs:${LOGS_PATH%/*}
      # - ./data/beets/library:${DATABASE_PATH%/*}
    ports:
      - 8337:8337
    environment:
      - TZ=Europe/Madrid
