version: '3.8'
services:
  beets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beets_watcher
    restart: always
    volumes:
      # If you want to use relative paths:
      - /volume1/docker/beets/config:/config
      # Or if you'd rather use absolute NAS paths:
      - /volume1/music/unsorted:/music_unsorted
      - /volume1/music/organized:/music_organized
    environment:
      - TZ=Europe/Madrid
