logging:
  level: debug

plugins:
  - lastgenre
  - info
  - the
  - inline
  - fuzzy
  - duplicates
  - unimported
  - mbsync
  - types
  - edit
  - convert
  - replaygain
  # - beatport4
  # - spotify
  - embedart
  - fetchart
  # - genrefallback
  - importadded
  # - subsonicupdate

include:
  - .configs/files.yaml
  - .configs/data.yaml
  - .configs/quality.yaml
  - .configs/sources.yaml
  - .configs/display.yaml